WebAppControleRestaurante/Models/ErrorViewModel.cs
namespace WebAppControleRestaurante.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebAppControleRestaurante/Models/PagtoMesaModel.cs
using Microsoft.VisualBasic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace WebAppControleRestaurante.Models
{
    public class PagtoMesaModel
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Cliente da mesa")] 
        public String Cliente { get; set; }
        [DisplayName("Data do pagamento")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:d}")]
        public DateFormat Data { get; set; }
        [Required(ErrorMessage = "Número da mesa")] 
        public int NumMesa { get; set; }
        [Required(ErrorMessage = "Valor do consumo da mesa")]
        [DisplayFormat(DataFormatString = "{0:C}")]
        public decimal ValConsumo { get; set; }
    }
}

WebAppControleRestaurante/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using WebAppControleRestaurante.Models;

namespace WebAppControleRestaurante.Controllers
{
    public class HomeController : Controller
    {

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
            /*view*/
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebAppControleRestaurante/Controllers/PagtoMesaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebAppControleRestaurante.Data;
using WebAppControleRestaurante.Models;

namespace WebAppControleRestaurante.Controllers
{
    public class PagtoMesaController : Controller
    {
        private readonly ApplicationDbContext _context;

        public PagtoMesaController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: PagtoMesaModels
        public async Task<IActionResult> Index()
        {
              return View(await _context.PagtoMesaModel.ToListAsync());
        }

        // GET: PagtoMesaModels/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.PagtoMesaModel == null)
            {
                return NotFound();
            }

            var pagtoMesaModel = await _context.PagtoMesaModel
                .FirstOrDefaultAsync(m => m.Id == id);
            if (pagtoMesaModel == null)
            {
                return NotFound();
            }

            return View(pagtoMesaModel);
        }

        // GET: PagtoMesaModels/Create
        [Authorize]
        public IActionResult Create()
        {
            return View();
        }

        // POST: PagtoMesaModels/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Cliente,NumMesa,ValConsumo")] PagtoMesaModel pagtoMesaModel)
        {
            if (ModelState.IsValid)
            {
                _context.Add(pagtoMesaModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(pagtoMesaModel);
        }

        // GET: PagtoMesaModels/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.PagtoMesaModel == null)
            {
                return NotFound();
            }

            var pagtoMesaModel = await _context.PagtoMesaModel.FindAsync(id);
            if (pagtoMesaModel == null)
            {
                return NotFound();
            }
            return View(pagtoMesaModel);
        }

        // POST: PagtoMesaModels/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Cliente,NumMesa,ValConsumo")] PagtoMesaModel pagtoMesaModel)
        {
            if (id != pagtoMesaModel.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(pagtoMesaModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PagtoMesaModelExists(pagtoMesaModel.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(pagtoMesaModel);
        }

        // GET: PagtoMesaModels/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.PagtoMesaModel == null)
            {
                return NotFound();
            }

            var pagtoMesaModel = await _context.PagtoMesaModel
                .FirstOrDefaultAsync(m => m.Id == id);
            if (pagtoMesaModel == null)
            {
                return NotFound();
            }

            return View(pagtoMesaModel);
        }

        // POST: PagtoMesaModels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.PagtoMesaModel == null)
            {
                return Problem("Entity set 'ApplicationDbContext.PagtoMesaModel'  is null.");
            }
            var pagtoMesaModel = await _context.PagtoMesaModel.FindAsync(id);
            if (pagtoMesaModel != null)
            {
                _context.PagtoMesaModel.Remove(pagtoMesaModel);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PagtoMesaModelExists(int id)
        {
          return _context.PagtoMesaModel.Any(e => e.Id == id);
        }
    }
}

WebAppControleRestaurante/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Página Inicial";
}

<div class="text-center">
    <h1 class="display-4">Restaurant of Course</h1>
    <p>Sistema de Pagamento de Restaurantes.</p>
</div>

WebAppControleRestaurante/Views/PagtoMesa/Create.cshtml
@model WebAppControleRestaurante.Models.PagtoMesaModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>PagtoMesaModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Cliente" class="control-label">Nome do cliente</label>
                <input asp-for="Cliente" class="form-control" />
                <span asp-validation-for="Cliente" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NumMesa" class="control-label">Número da mesa</label>
                <input asp-for="NumMesa" class="form-control" />
                <span asp-validation-for="NumMesa" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ValConsumo" class="control-label">Valor do consumo</label>
                <input asp-for="ValConsumo" class="form-control" />
                <span asp-validation-for="ValConsumo" class="text-danger"></span>
            </div>
            @{
                <div class="d-grid gap-2">
                    <button type="submit" class="btn btn-primary ">Fechar mesa</button>
                    <a class="btn btn-secondary" asp-controller="PagtoMesa" asp-action="Index" role="button">Voltar</a>
                </div>
            }
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebAppControleRestaurante/Views/PagtoMesa/Delete.cshtml
@model WebAppControleRestaurante.Models.PagtoMesaModel

@{
    ViewData["Title"] = "Apagar pagamento";
}

<h1>Apagar pagamento da mesa</h1>

<h3>Confirma?</h3>
<div>
    <h4>Você está prestes a apagar o pagamento abaixo:</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            <label asp-for="Cliente" class="control-label">Nome do cliente</label>
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Cliente)
        </dd>
        <dt class="col-sm-2">
            <label asp-for="NumMesa" class="control-label">Número da mesa</label>
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.NumMesa)
        </dd>
        <dt class="col-sm-2">
            <label asp-for="ValConsumo" class="control-label">Valor do consumo</label>
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ValConsumo)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Apagar pagamento" class="btn btn-danger" />
        <a class="btn btn-secondary" asp-controller="PagtoMesa" asp-action="Index" role="button">Voltar</a>
        
    </form>
</div>

WebAppControleRestaurante/Views/PagtoMesa/Details.cshtml
@model WebAppControleRestaurante.Models.PagtoMesaModel

@{
    ViewData["Title"] = "Details";
}

<h1>Detalhe do pagamento</h1>

<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            <label asp-for="Cliente" class="control-label">Nome do cliente</label>
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cliente)
        </dd>
        <dt class = "col-sm-2">
            <label asp-for="Cliente" class="control-label">Número da mesa</label>
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NumMesa)
        </dd>
        <dt class="col-sm-2">
            <label asp-for="Cliente" class="control-label">Valor do consumo</label>
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ValConsumo)
        </dd>
    </dl>
</div>
<div>
    <a role="button" class="btn btn-secondary" asp-controller="PagtoMesa" asp-route-id="@Model?.Id" asp-action="Edit">Editar</a>
    <a class="btn btn-secondary" asp-controller="PagtoMesa" asp-action="Index" role="button">Voltar</a>
</div>

WebAppControleRestaurante/Views/PagtoMesa/Edit.cshtml
@model WebAppControleRestaurante.Models.PagtoMesaModel

@{
    ViewData["Title"] = "Editar pagamento";
}

<h1>Editar pagamento</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Cliente" class="control-label">Nome do cliente</label>
                <input asp-for="Cliente" class="form-control" placeholder="Nome do cliente" />
                <span asp-validation-for="Cliente" class="text-danger"> </span>
                @Html.ValidationMessageFor(x =>x.Cliente)
            </div>
            <div class="form-group">
                <label asp-for="NumMesa" class="control-label">Número da mesa</label>
                <input asp-for="NumMesa" class="form-control" placeholder="Número da mesa" />
                <span asp-validation-for="NumMesa" class="text-danger"> </span>
                @Html.ValidationMessageFor(x =>x.NumMesa)
            </div>
            <div class="form-group">
                <label asp-for="ValConsumo" class="control-label">Valor do consumo</label>
                <input asp-for="ValConsumo" class="form-control" placeholder="Valor do consumo" />
                <span asp-validation-for="ValConsumo" class="text-danger"> </span>
                @Html.ValidationMessageFor(x =>x.ValConsumo)
            </div>
            @{
            <div class="d-grid gap-2">
                 <button type="submit" class="btn btn-primary ">Alterar Pagamento</button>
                 <a class="btn btn-secondary" asp-controller="PagtoMesa" asp-action="Index" role="button">Voltar</a>
            </div>
            }
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebAppControleRestaurante/Views/PagtoMesa/Index.cshtml
@model IEnumerable<WebAppControleRestaurante.Models.PagtoMesaModel>

@{
    ViewData["Title"] = "Relação de Pagamentos";
}

<h1>Relação de pagamentos por mesa</h1>

<p>
    <div class="d-grid gap-2 d-md-flex justify-content-md-start">
        <a class="btn btn-primary" asp-controller="PagtoMesa" asp-action="Create" role="button">Fechar consumo da mesa</a>
    </div>

</p>
<table id="table-PagtoMesaModel" class="display" runat="server">
    <thead>
         <tr>
            <th scope="col">#</th>
            <th scope="col">Nome do cliente</th>
            <th scope="col">Número da mesa</th>
            <th scope="col">Valor do consumo</th> 
            <th scope="col">Data</th> 
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
     @if (Model != null)
     {
            @foreach (var item in Model)
            {
            <tr>
             <th scope="row">
                @Html.DisplayFor(modelItem => item.Id)
            </th>
            <td>
                @Html.DisplayFor(modelItem => item.Cliente)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NumMesa)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ValConsumo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Data)
            </td>
            <td>
                <div class="btn-group" role="button">
                    <a role="button" class="btn btn-primary" asp-controller="PagtoMesa" asp-route-id="@item.Id" asp-action="Details">Detalhar</a>
                    <a role="button" class="btn btn-secondary" asp-controller="PagtoMesa" asp-route-id="@item.Id" asp-action="Edit">Editar</a>
                    <a role="button" class="btn btn-danger"  asp-controller="PagtoMesa" asp-route-id="@item.Id" asp-action="Delete">Apagar</a>
                </div>
            </td>
        </tr>
    }
}
    </tbody>
</table>

WebAppControleRestaurante/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebAppControleRestaurante</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebAppControleRestaurante.styles.css" asp-append-version="true" />
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/dt-1.13.1/datatables.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebAppControleRestaurante</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Página inicial">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="PagtoMesa" asp-action="Index">Pagamentos das mesas</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - WebAppControleRestaurante - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/v/dt/dt-1.13.1/datatables.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>